export class ItiReportDataModel {
  public Eid:number=0
  public RoleID:number=0
  public PanchayatId:number=0
  public CollegeID: number = 0
  public CollegeName: string = ''
  public LandTypeID: string = ''
  public Loksabha:string=''
  public Vidhansabha:string=''
  public LandAvailable:string=''
  public PanchayatDis:string=''
  public SanctionOrderNo:string=''
  public MetpOrderNo:string=''
  public MetpOrderDate:string=''
  public SanctionOrderDate:string=''
  public MetpCopy:string=''
  public TradeOrderNo:string=''
  public AdministrativeOrderNo:string=''
  public ElectPhaserequired:string=''
  public TradeOrderDate:string=''
  public AdministrativeOrderDate:string=''
  public ApproachRoad:string=''
  public InternalRoad:string=''
  public WaterSupply:string=''
  public Harvesting:string=''
  public ElectPhase:string=''
  public ElectConnection:string=''
  public IsSolarPanel:string=''
  public PanelCapacity:string=''
  public ContractLoad:string=''
  public IsBoundaryWall:string=''
  public ShilanyasPost:string=''
  public BuildShortage:string=''
  public IsHostel:string=''
  public HostelUtilized:string=''
  public NoOfTree:string=''
  public Remarks:string=''
  public FrontPhoto:string=''
  public SidePhoto:string=''
  public CompleteDate:string=''
  public StartDate:string=''
  public InteriorPhoto:string=''
  public SanctionOrderCopy:string=''
  public TradeCopy:string=''
  public AdministrativeCopy:string=''
  public ConstructionAgency:string=''
  public PDName:string=''
  public ContractorName:string=''
  public PDMobile:string=''
  public ContractorMobile:string=''
  public IsDispute:string=''
  public FinancialSanction:string=''
  public FinancialCopy: string = ''
  public PercentCivilWork: string = ''
  public PercentCivilDate: string = ''
  public IsPurposeHall: string = ''
  public IsMainITI: string = ''
  public IsBuildingTaken: string = ''
  public TakenOverDate: string = ''
  public IsOperatingOwn:string=''
  public ShilanyasDate:string=''
  public LokarpanDate:string=''
  public LokarpanName:string=''
  public LokarpanPost:string=''
  public AllotmentLetter:string=''
  public BuildingPlanCopy:string=''
  public DomeViewCopy: string = ''
  public WorkOrderCopy: string = ''
  public ShilanyasName: string = ''
  public PrincipleName: string = ''
  public PrincipleMobile: string = ''
  public PrincipleEmailID: string = ''
  public Pincode: string = ''
  public LandAddress: string = ''
  public IsNewCollege: number = 0
  public ModifyBy:number=0
  public Category:number=0
  public Esttablishment_Year: number = 0
  public FinancialSanctionList: any[] = []
  public BasicDetailsList: any[] = []
  public UpdateWorkList: any[] = []
  public AnnoucementType: number = 0
  public DistrictID: number = 0
  public UrbanRural: number = 0
  public DivisionID: number = 0
  public TehsilID: number = 0
  public GramPanchayatSamiti: number = 0
  public VillageID: number = 0
  public CityID: number = 0
  public AdministrativeBodyId: number = 0
  public SubDivisionID: number = 0
  public OrderType: number = 0
  public OrderDetailsList: any[] = []
  public WorkStarted:string=''
  public WorkName:string=''
  public WorkTradeCopy:string=''
  public WorkFSCopy:string=''
  public WorkConstructor:string=''
  public WorkCopy:string=''
  public UpdateWorkStarted:string=''
  public UpdateExpectedDate:string=''
  public WorkSanctionCopy:string=''
  public UpdatePercentWork:string=''
  public UpdateRemarks: string = ''
  public OrderTypeID:number=0

}

export class ItiSanctionOrderList {
  public SanctionID :number=0
  public OrderType :number=0
  public InstituteID :number=0
  public ModifyBy :number=0
  public OrderNo :string=''
  public OrderDate :string=''
  public OrderCopy: string = ''


}
